package:
  name: pygof
  version: "0.1.1"
 
source:
  path: ../
 
requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
  run:
    - python
    - numpy
    - scipy
 
test:
  imports:
    - pygof
 
about:
  home: https://github.com/willfurnass/pygof
  license: GPL 3.0
  license_file: LICENSE.txt
